version: '3.8'

services:
  ecommerceapp:
    build: ./
    ports: 
    - '3000:3000'
    env_file: 
    - .env.development
    depends_on: 
    - ecommercedb

  ecommercedb:
    image: 'postgres'
    volumes: 
    - pgdata:/var/lib/postgresql/data
    env_file: 
    - .env.development

volumes:
 pgdata: